%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#2196f3', 'edgeLabelBackground':'#f9f9f9', 'tertiaryColor': '#e1e4e8'}} }%%
graph TD
    classDef frozen fill:#e1e4e8,stroke:#333,stroke-dasharray: 5 5;
    classDef trainable fill:#c8e6c9,stroke:#2e7d32,stroke-width:2px;
    classDef hyperbolic fill:#e1bee7,stroke:#7b1fa2,stroke-width:2px;
    
    %% Hyperbolic Projection

    Z_euc[Euclidean Z] -->|Copy| Branch1
    Z_euc -->|Copy| Branch2
    
    subgraph Direction Learning
    Branch1 --> DirNet[Direction Net]:::trainable
    DirNet -->|Residual| Add[+]
    Branch1 --> Add
    Add --> Norm[Normalize L2]
    Norm --> Dir[Direction Vector]
    end
    
    subgraph Radial Learning
    Branch2 --> RadNet[Radius Net]:::trainable
    RadNet --> Sigmoid
    Sigmoid --> Scale[Scale by MaxRadius]
    Scale --> Rad[Scalar Radius]
    end
    
    Dir --> Mult[Multiply]
    Rad --> Mult
    Mult --> Z_hyp[Poincaré Z]:::hyperbolic